# Set as [environment]-schema in SPRING_PROFILES_ACTIVE
# Environments include: local, dev, docker, prod. See MultiTenantConfiguration.java

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://TBD/norpac?currentSchema=norpac_commons
    username: web_update 
    password: 
    
logging:
  level:
    com.norpactech.nc: WARN

cognito:
  region: 'us-west-2'
  user-pool-id: 'us-west-2_JR6P3syVo'
  user-pool-client-id: '23mkuh54op72ur6sb5urgf027o'
  user-pool-client-secret: ${COGNITO_CLIENT_SECRET}